"""Legacy curated emoji data kept for backwards compatibility.

REACTION_EMOJI and SKIN_TONE_CAPABLE were extracted from emoji_picker.py
(plan 0020/0021) when plan 0027 moved the picker into the standalone
textual-emoji-picker package.  They remain importable from this module so
that existing callers do not break.  Remove this file in plan 0028 once all
callers have been updated to use the library's full set.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Curated reaction emoji set (~80 entries from Element Web default reactions)
# (codepoint, search-name) — names are used for filtering only
# ---------------------------------------------------------------------------

REACTION_EMOJI: list[tuple[str, str]] = [
    # Faces / expressions
    ("😀", "grinning face"),
    ("😁", "beaming face with smiling eyes"),
    ("😂", "face with tears of joy"),
    ("🤣", "rolling on the floor laughing"),
    ("😃", "grinning face with big eyes"),
    ("😄", "grinning face with smiling eyes"),
    ("😅", "grinning face with sweat"),
    ("😆", "grinning squinting face"),
    ("😉", "winking face"),
    ("😊", "smiling face with smiling eyes"),
    ("😋", "face savoring food"),
    ("😎", "smiling face with sunglasses"),
    ("😍", "smiling face with heart-eyes"),
    ("🥰", "smiling face with hearts"),
    ("😘", "face blowing a kiss"),
    ("😗", "kissing face"),
    ("🙂", "slightly smiling face"),
    ("🙃", "upside down face"),
    ("😐", "neutral face"),
    ("😑", "expressionless face"),
    ("😶", "face without mouth"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("😏", "smirking face"),
    ("😒", "unamused face"),
    ("🙄", "face with rolling eyes"),
    ("😬", "grimacing face"),
    ("🤥", "lying face"),
    ("😔", "pensive face"),
    ("😪", "sleepy face"),
    ("🤤", "drooling face"),
    ("😴", "sleeping face"),
    ("😷", "face with medical mask"),
    ("🤒", "face with thermometer"),
    ("🤕", "face with head-bandage"),
    ("🤢", "nauseated face"),
    ("🤮", "face vomiting"),
    ("🤧", "sneezing face"),
    ("😵", "dizzy face"),
    ("🤯", "exploding head"),
    ("🤠", "cowboy hat face"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("👿", "angry face with horns"),
    ("👻", "ghost"),
    ("💀", "skull"),
    ("🤡", "clown face"),
    ("👾", "alien monster"),
    ("🤖", "robot"),
    ("😺", "grinning cat"),
    ("😸", "grinning cat with smiling eyes"),
    ("😹", "cat with tears of joy"),
    ("😻", "smiling cat with heart-eyes"),
    ("😿", "crying cat"),
    # Gestures / hands
    ("👍", "thumbs up"),
    ("👎", "thumbs down"),
    ("👌", "ok hand"),
    ("🤌", "pinched fingers"),
    ("✌️", "victory hand"),
    ("🤞", "crossed fingers"),
    ("🤟", "love-you gesture"),
    ("🤘", "sign of the horns"),
    ("👏", "clapping hands"),
    ("🙌", "raising hands"),
    ("🤲", "palms up together"),
    ("🙏", "folded hands"),
    ("🤝", "handshake"),
    ("💪", "flexed biceps"),
    ("✍️", "writing hand"),
    ("👀", "eyes"),
    ("🫶", "heart hands"),
    ("🫱", "rightwards hand"),
    ("🫲", "leftwards hand"),
    ("🫳", "palm down hand"),
    ("🫴", "palm up hand"),
    ("🫵", "index pointing at viewer"),
    ("👆", "backhand index pointing up"),
    ("👇", "backhand index pointing down"),
    ("👈", "backhand index pointing left"),
    ("👉", "backhand index pointing right"),
    ("☝️", "index pointing up"),
    ("✋", "raised hand"),
    ("🤚", "raised back of hand"),
    ("🖐️", "hand with fingers splayed"),
    ("🖖", "vulcan salute"),
    ("🤙", "call me hand"),
    ("🦾", "mechanical arm"),
    ("🦿", "mechanical leg"),
    # Hearts / symbols
    ("❤️", "red heart"),
    ("🧡", "orange heart"),
    ("💛", "yellow heart"),
    ("💚", "green heart"),
    ("💙", "blue heart"),
    ("💜", "purple heart"),
    ("🖤", "black heart"),
    ("🤍", "white heart"),
    ("💔", "broken heart"),
    ("❣️", "heart exclamation"),
    ("💕", "two hearts"),
    ("💞", "revolving hearts"),
    ("💓", "beating heart"),
    ("💗", "growing heart"),
    ("💖", "sparkling heart"),
    ("💘", "heart with arrow"),
    ("💝", "heart with ribbon"),
    # Misc reactions
    ("🔥", "fire"),
    ("💯", "hundred points"),
    ("💥", "collision"),
    ("⭐", "star"),
    ("✨", "sparkles"),
    ("🎉", "party popper"),
    ("🎊", "confetti ball"),
    ("🤦", "person facepalming"),
    ("🤷", "person shrugging"),
    ("👋", "waving hand"),
    ("🫡", "saluting face"),
    ("😮", "face with open mouth"),
    ("😲", "astonished face"),
    ("😯", "hushed face"),
]


# ---------------------------------------------------------------------------
# Skin-tone support
# ---------------------------------------------------------------------------

# Base codepoints that accept a Fitzpatrick modifier — conservative whitelist
# from the original curated set.
SKIN_TONE_CAPABLE: frozenset[str] = frozenset(
    {
        "👍",
        "👎",
        "👌",
        "🤌",
        "🤞",
        "🤟",
        "🤘",
        "👏",
        "🙌",
        "🤲",
        "🙏",
        "💪",
        "🫶",
        "🫱",
        "🫲",
        "🫳",
        "🫴",
        "🫵",
        "👆",
        "👇",
        "👈",
        "👉",
        "✋",
        "🤚",
        "🖖",
        "🤙",
        "🤦",
        "🤷",
        "👋",
        "✊",
        "👊",
        "🤛",
        "🤜",
    }
)
